# Generated by Django 5.2.17 on 2026-09-03 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pause_rotation', models.BooleanField(default=False)),
                ('default_interval_days', models.IntegerField(default=3)),
                ('invite_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('partners', models.ManyToManyField(related_name='households', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
