# Generated by Django 5.2.17 on 2026-09-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0002_category_chore_choreassignment_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('reminder', 'Reminder'), ('overdue', 'Overdue')], default='reminder', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('chore_assignment', 'notification_type')},
        ),
    ]
